---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "www/js/*.js"
  - "www/js/**/*.js"
exclude_paths: 
  - "www/lib/"
  - "coverage/"
