
language: node_js
node_js:
  - "7"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g cordova ionic

script:
  - ionic cordova run android --prod
  - ionic cordova run ios --prod
  
notifications:
  email:
    recipients:
      - andrade.icaa@gmail.com
      - annalarissa.mmm@gmail.com
      - gabrielaalvesdagama@gmail.com
      - halevalente@gmail.com
      - lhqmalta@gmail.com
      - mare.s.mendes@gmail.com
      
     
      
