language: node_js

rvm:
  - "4.5.0"

install:
 - npm install -g karma --save-dev

before_script:
 - npm install -g karma-jasmine
 - npm install -g phantomjs --save-dev
 - npm install -g karma-phantomjs-launcher --save-dev
 - npm install -g karma-coverage --save-dev

script:
  - karma start --single-run --browsers PhantomJS

notifications:
  email:
    recipients:
      - antoniojk7@gmail.com
      - leomeister22@gmail.com
      - lucas.advc@gmail.com
      - skingk.f@gmail.com
      - vitor.nere@hotmail.com

