language: node_js

node_js:
  - "node"

addons:
  chrome: stable

before_script:
  - npm install
  - npm install -g @ionic/cli-framework
  - set -e

script:
  - ionic serve


notifications:
  email:
    recipients:
      - andrade.icaa@gmail.com
      
