version: '2.0'

services:
  ionic:
    build: .
    command: 'ionic serve --all'
    ports:
      - 8100:8100
      - 35729:35729
      - 53703:53703
    volumes:
      - .:/code
      - /code/node_modules
